-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/8/2014 11:35:23 PM
-- Server version: 5.6.14
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE gigi;

--
-- Definition for table borallastock
--
DROP TABLE IF EXISTS borallastock;
CREATE TABLE borallastock (
  ItemCode VARCHAR(10) NOT NULL,
  `1` INT(11) DEFAULT NULL,
  `2` INT(11) DEFAULT NULL,
  `3` INT(11) DEFAULT NULL,
  `4` INT(11) DEFAULT NULL,
  `5` INT(11) DEFAULT NULL,
  `6` INT(11) DEFAULT NULL,
  `7` INT(11) DEFAULT NULL,
  `8` INT(11) DEFAULT NULL,
  `9` INT(11) DEFAULT NULL,
  `10` INT(11) DEFAULT NULL,
  `11` INT(11) DEFAULT NULL,
  `12` INT(11) DEFAULT NULL,
  Total INT(11) DEFAULT NULL,
  Last_updated DATE DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table borallatransaction
--
DROP TABLE IF EXISTS borallatransaction;
CREATE TABLE borallatransaction (
  TransDate DATE NOT NULL,
  InvoiceNumber VARCHAR(10) NOT NULL,
  SeqNo INT(11) NOT NULL,
  ItemCode VARCHAR(10) NOT NULL,
  InvoiceType INT(11) NOT NULL,
  Size INT(11) NOT NULL,
  Pairs INT(11) NOT NULL,
  Price DECIMAL(10, 0) NOT NULL,
  Discount DECIMAL(10, 0) DEFAULT NULL,
  DiscountAmount DECIMAL(10, 0) DEFAULT NULL,
  NetValue DECIMAL(10, 0) DEFAULT NULL,
  InvoiceValue DECIMAL(10, 0) NOT NULL,
  PRIMARY KEY (TransDate, InvoiceNumber, SeqNo)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table design
--
DROP TABLE IF EXISTS design;
CREATE TABLE design (
  ItemCode VARCHAR(10) NOT NULL,
  Category INT(11) DEFAULT NULL,
  Vendor VARCHAR(50) DEFAULT NULL,
  Remarks VARCHAR(100) DEFAULT NULL,
  Units INT(11) DEFAULT NULL,
  Date DATE DEFAULT NULL,
  ManufacturedDate DATE DEFAULT NULL,
  CostPrice DECIMAL(8, 2) NOT NULL,
  SLPSellingPrice DECIMAL(8, 2) DEFAULT NULL,
  ShopSellingPrice DECIMAL(8, 2) DEFAULT NULL,
  LobbySalePrice DECIMAL(8, 2) DEFAULT NULL,
  MOPrice DECIMAL(8, 2) DEFAULT NULL,
  ImagePath VARCHAR(150) DEFAULT NULL,
  ModifiedBy VARCHAR(50) DEFAULT NULL,
  ModifiedDate DATE DEFAULT NULL,
  Description VARCHAR(300) DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table employee
--
DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
  employeeId INT(11) NOT NULL,
  FName VARCHAR(20) DEFAULT NULL,
  LName VARCHAR(50) DEFAULT NULL,
  Tp INT(11) DEFAULT NULL,
  PRIMARY KEY (employeeId)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table invoicetype
--
DROP TABLE IF EXISTS invoicetype;
CREATE TABLE invoicetype (
  TypeId INT(11) NOT NULL,
  TypeName VARCHAR(20) NOT NULL,
  PRIMARY KEY (TypeId)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table mcstock
--
DROP TABLE IF EXISTS mcstock;
CREATE TABLE mcstock (
  ItemCode VARCHAR(10) NOT NULL,
  `1` INT(11) DEFAULT NULL,
  `2` INT(11) DEFAULT NULL,
  `3` INT(11) DEFAULT NULL,
  `4` INT(11) DEFAULT NULL,
  `5` INT(11) DEFAULT NULL,
  `6` INT(11) DEFAULT NULL,
  `7` INT(11) DEFAULT NULL,
  `8` INT(11) DEFAULT NULL,
  `9` INT(11) DEFAULT NULL,
  `10` INT(11) DEFAULT NULL,
  `11` INT(11) DEFAULT NULL,
  `12` INT(11) DEFAULT NULL,
  Total INT(11) DEFAULT NULL,
  Last_updated DATE DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table mctransaction
--
DROP TABLE IF EXISTS mctransaction;
CREATE TABLE mctransaction (
  TransDate DATE NOT NULL,
  InvoiceNumber VARCHAR(10) NOT NULL,
  SeqNo INT(11) NOT NULL,
  ItemCode VARCHAR(10) NOT NULL,
  InvoiceType INT(11) NOT NULL,
  Size INT(11) NOT NULL,
  Pairs INT(11) NOT NULL,
  Price DECIMAL(10, 0) NOT NULL,
  Discount DECIMAL(10, 0) DEFAULT NULL,
  DiscountAmount DECIMAL(10, 0) DEFAULT NULL,
  NetValue DECIMAL(10, 0) DEFAULT NULL,
  InvoiceValue DECIMAL(10, 0) NOT NULL,
  PRIMARY KEY (TransDate, InvoiceNumber, SeqNo)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table nugegodastock
--
DROP TABLE IF EXISTS nugegodastock;
CREATE TABLE nugegodastock (
  ItemCode VARCHAR(10) NOT NULL,
  `1` INT(11) DEFAULT NULL,
  `2` INT(11) DEFAULT NULL,
  `3` INT(11) DEFAULT NULL,
  `4` INT(11) DEFAULT NULL,
  `5` INT(11) DEFAULT NULL,
  `6` INT(11) DEFAULT NULL,
  `7` INT(11) DEFAULT NULL,
  `8` INT(11) DEFAULT NULL,
  `9` INT(11) DEFAULT NULL,
  `10` INT(11) DEFAULT NULL,
  `11` INT(11) DEFAULT NULL,
  `12` INT(11) DEFAULT NULL,
  Total INT(11) DEFAULT NULL,
  Last_updated DATE DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table nugegodatransaction
--
DROP TABLE IF EXISTS nugegodatransaction;
CREATE TABLE nugegodatransaction (
  TransDate DATE NOT NULL,
  InvoiceNumber VARCHAR(10) NOT NULL,
  SeqNo INT(11) NOT NULL,
  ItemCode VARCHAR(10) NOT NULL,
  InvoiceType INT(11) NOT NULL,
  Size INT(11) NOT NULL,
  Pairs INT(11) NOT NULL,
  Price DECIMAL(10, 0) NOT NULL,
  Discount DECIMAL(10, 0) DEFAULT NULL,
  DiscountAmount DECIMAL(10, 0) DEFAULT NULL,
  NetValue DECIMAL(10, 0) DEFAULT NULL,
  InvoiceValue DECIMAL(10, 0) DEFAULT NULL,
  PRIMARY KEY (TransDate, InvoiceNumber, SeqNo)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table stock
--
DROP TABLE IF EXISTS stock;
CREATE TABLE stock (
  ItemCode VARCHAR(10) NOT NULL,
  `1` INT(11) DEFAULT NULL,
  `2` INT(11) DEFAULT NULL,
  `3` INT(11) DEFAULT NULL,
  `4` INT(11) DEFAULT NULL,
  `5` INT(11) DEFAULT NULL,
  `6` INT(11) DEFAULT NULL,
  `7` INT(11) DEFAULT NULL,
  `8` INT(11) DEFAULT NULL,
  `9` INT(11) DEFAULT NULL,
  `10` INT(11) DEFAULT NULL,
  `11` INT(11) DEFAULT NULL,
  `12` INT(11) DEFAULT NULL,
  Total INT(11) DEFAULT NULL,
  Last_updated DATE DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table stocktransaction
--
DROP TABLE IF EXISTS stocktransaction;
CREATE TABLE stocktransaction (
  ItemCode VARCHAR(10) NOT NULL,
  `1` INT(11) DEFAULT NULL,
  `2` INT(11) DEFAULT NULL,
  `3` INT(11) DEFAULT NULL,
  `4` INT(11) DEFAULT NULL,
  `5` INT(11) DEFAULT NULL,
  `6` INT(11) DEFAULT NULL,
  `7` INT(11) DEFAULT NULL,
  `8` INT(11) DEFAULT NULL,
  `9` INT(11) DEFAULT NULL,
  `10` INT(11) DEFAULT NULL,
  `11` INT(11) DEFAULT NULL,
  `12` INT(11) DEFAULT NULL,
  Total INT(11) NOT NULL,
  Date INT(11) DEFAULT NULL,
  Status INT(11) NOT NULL,
  `From` VARCHAR(20) NOT NULL,
  `To` VARCHAR(20) NOT NULL,
  Remarks VARCHAR(100) DEFAULT NULL,
  RefNo VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (ItemCode)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table borallastock
--

-- Table gigi.borallastock does not contain any data (it is empty)

-- 
-- Dumping data for table borallatransaction
--

-- Table gigi.borallatransaction does not contain any data (it is empty)

-- 
-- Dumping data for table design
--

-- Table gigi.design does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--

-- Table gigi.employee does not contain any data (it is empty)

-- 
-- Dumping data for table invoicetype
--

-- Table gigi.invoicetype does not contain any data (it is empty)

-- 
-- Dumping data for table mcstock
--

-- Table gigi.mcstock does not contain any data (it is empty)

-- 
-- Dumping data for table mctransaction
--

-- Table gigi.mctransaction does not contain any data (it is empty)

-- 
-- Dumping data for table nugegodastock
--

-- Table gigi.nugegodastock does not contain any data (it is empty)

-- 
-- Dumping data for table nugegodatransaction
--

-- Table gigi.nugegodatransaction does not contain any data (it is empty)

-- 
-- Dumping data for table stock
--

-- Table gigi.stock does not contain any data (it is empty)

-- 
-- Dumping data for table stocktransaction
--

-- Table gigi.stocktransaction does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;